### ISSUE TITLE
Install Booleannet

### ISSUE THREAD

**Issue by priyambial123** [ialbert/booleannet#2]
Hi,
I have installed Python 2.5 in my system (Windows, 64 bit) but still can't install BooleanNet. 
Error message when tried to open in command prompt:

Microsoft Windows Version 10.0.10586 2015 Microsoft Corporation. All rights reserved.

C:\Users\Priya>cd C:\Users\Priya\Desktop\Booleannet-new

C:\Users\Priya\Desktop\Booleannet-new>python setup.py install
Traceback (most recent call last):
File "setup.py", line 3, in 
import boolean2
File "C:\Users\Priya\Desktop\Booleannet-new\boolean2__init__.py", line 61
print all_nodes ( text )
^
SyntaxError: invalid syntax

Thank you
Priya

**Comment by priyambial123** [comment]
Error message when tried to open in command prompt:

Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Priya>python setup.py install
python: can't open file 'setup.py': [Errno 2] No such file or directory

C:\Users\Priya>cd C:\Users\Priya\Desktop\Booleannet-new

C:\Users\Priya\Desktop\Booleannet-new>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    import boolean2
  File "C:\Users\Priya\Desktop\Booleannet-new\boolean2\__init__.py", line 61
    print all_nodes ( text )
                  ^
SyntaxError: invalid syntax

C:\Users\Priya\Desktop\Booleannet-new>

**Comment by priyambial123** [comment]
Hi,
   I could install Booleannet succesfully in Python 2.7 (RedHat Linux). I couldn't install in Python 2.5. Since in the installation instructions page, it has been mentioned that Python 2.5 is required, I have been struggling to install Booleannet in my Linux and Windows workstations for a long time. But now I could install with Python 2.7 in my Linux workstation, didn't try in Windows.
Regards
Priya
