### ISSUE TITLE
I cant install the module

### ISSUE THREAD

**Issue by vsraptor** [ialbert/booleannet#4]
```
# pip install BooleanNet
Collecting BooleanNet
  Using cached BooleanNet-1.2.8.tar.gz (389 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j8jus021/BooleanNet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-j8jus021/BooleanNet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-j8jus021/BooleanNet/pip-egg-info
         cwd: /tmp/pip-install-j8jus021/BooleanNet/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-j8jus021/BooleanNet/setup.py", line 3, in <module>
        import boolean2
      File "/tmp/pip-install-j8jus021/BooleanNet/boolean2/__init__.py", line 61
        print all_nodes ( text )
                      ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by ialbert** [comment]
This version requires Python 2.7

**Comment by ialbert** [comment]
There is a Python 3 fork that may be usable here:

https://github.com/Natay/booleannet

**Comment by vsraptor** [comment]
i see ...

this worked :+1: 

     pip2 install BooleanNet

**Comment by ialbert** [comment]
I have updated the installation instructions here:

https://github.com/ialbert/booleannet/blob/master/README.md
